/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasitas;

import java.text.SimpleDateFormat;
import java.util.Set;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aldy
 */
public class Jframe_Tas extends javax.swing.JFrame {
    //untuk mendeklarasikan Variable.
    String hasil = "";
    String date ;
    String Nilai ="";
   

    /**
     * Creates new form Jframe_Tas
     */
    public Jframe_Tas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngnilai = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        cmbMerek = new javax.swing.JComboBox<>();
        ckHijau = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txthasil = new javax.swing.JTextArea();
        btnBersihkan = new javax.swing.JButton();
        btnBayarkan = new javax.swing.JButton();
        btnSelesai = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        ckHitam = new javax.swing.JCheckBox();
        ckBiru = new javax.swing.JCheckBox();
        ckCampuran = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rdpuas = new javax.swing.JRadioButton();
        ckTidak = new javax.swing.JCheckBox();
        rdtidak = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 102));

        jLabel1.setBackground(new java.awt.Color(204, 204, 0));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("    Aplikasi Tas Sekolah 2018");

        txtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahActionPerformed(evt);
            }
        });

        cmbMerek.setBackground(new java.awt.Color(51, 51, 255));
        cmbMerek.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbMerek.setForeground(new java.awt.Color(255, 255, 255));
        cmbMerek.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADIDAS", "NIKE", "VANS", "EIGER", "REY", "BILABONG" }));
        cmbMerek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMerekActionPerformed(evt);
            }
        });

        ckHijau.setText("HIJAU");
        ckHijau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckHijauActionPerformed(evt);
            }
        });

        txthasil.setColumns(20);
        txthasil.setRows(5);
        jScrollPane1.setViewportView(txthasil);

        btnBersihkan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBersihkan.setText("Bersihkan");
        btnBersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBersihkanActionPerformed(evt);
            }
        });

        btnBayarkan.setBackground(new java.awt.Color(255, 102, 102));
        btnBayarkan.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnBayarkan.setText("Bayarkan");
        btnBayarkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarkanActionPerformed(evt);
            }
        });

        btnSelesai.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnSelesai.setText("Selesai");
        btnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelesaiActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 51, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Jumlah Pembelian");

        ckHitam.setText("HITAM");
        ckHitam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckHitamActionPerformed(evt);
            }
        });

        ckBiru.setForeground(new java.awt.Color(0, 0, 255));
        ckBiru.setText("BIRU");

        ckCampuran.setText("CAMPURAN");

        jLabel3.setText("Warna TAS :");

        jLabel4.setText("Pilih Nilai Untuk produk ini :");

        rdpuas.setBackground(new java.awt.Color(0, 51, 255));
        btngnilai.add(rdpuas);
        rdpuas.setText("Puas");
        rdpuas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdpuasActionPerformed(evt);
            }
        });

        ckTidak.setForeground(new java.awt.Color(255, 51, 51));
        ckTidak.setText("Tidak Memilih");

        rdtidak.setBackground(new java.awt.Color(255, 51, 102));
        btngnilai.add(rdtidak);
        rdtidak.setText("Tidak Puas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckHitam)
                            .addComponent(ckHijau))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckCampuran)
                            .addComponent(ckBiru))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(84, 84, 84))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(43, 43, 43)
                                            .addComponent(txtJumlah))
                                        .addComponent(btnBayarkan, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnBersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(ckTidak)
                                        .addComponent(cmbMerek, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(72, 72, 72)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(rdtidak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(rdpuas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGap(0, 0, Short.MAX_VALUE)))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbMerek, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ckHitam)
                            .addComponent(ckBiru)
                            .addComponent(ckTidak))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ckHijau)
                            .addComponent(ckCampuran))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(rdpuas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdtidak)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSelesai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(btnBersihkan))
                    .addComponent(btnBayarkan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtJumlahActionPerformed

    private void ckHijauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckHijauActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ckHijauActionPerformed

    private void cmbMerekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMerekActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbMerekActionPerformed

    private void btnBayarkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarkanActionPerformed
        // Inisilalisai data penampung
            String Harga = "";
            String Merek = "";
            String Ucapan = "";
            String Warna = "";
            String Kepuasan = "";
            Kepuasan ="";
            float JumlahPembayaran  = 0 ;
            int Jumlah = 0 ;
           
        // Inisialisasi seleksi data 
            switch(cmbMerek.getSelectedIndex()){
                case 0       :
                    JumlahPembayaran = Float.parseFloat(txtJumlah.getText());
                    Jumlah = (int) Float.parseFloat(txtJumlah.getText());
                    JumlahPembayaran = (float) (JumlahPembayaran*200000);
                    Jumlah = (int) (Jumlah);
                    Harga = " Harga                           : Rp 200.000";
                    Merek = " Merek                           : ADIDAS";
                    Ucapan =" Ucapan Dari Kami    : Terima Kasih, Puas atau Tidak kami akan selalu memperbaiki pelayanan Kami !";
        // Iniasialisai seleksi data Warna           
                    if (ckHitam.isSelected()) {
                        Warna += ckHitam.getText() + ", ";
                    }
                    if (ckHijau.isSelected()) {
                        Warna += ckHijau.getText() + ", ";
                    }
                    if (ckBiru.isSelected()) {
                        Warna += ckBiru.getText() + ", ";
                    }
                    if (ckCampuran.isSelected()) {
                        Warna += ckCampuran.getText() + ", ";
                    }
                    if (ckTidak.isSelected()) {
                        Warna += ckTidak.getText() + ", ";
                    }else {
                        Warna = Warna.substring(0, Warna.length()-2) + ", ";
                    }
        // Inisialisai seleksi data Nilai Kepuasan
                    if (rdpuas.isSelected()){
                        Kepuasan = rdpuas.getText();
                    }else{
                        Kepuasan = rdtidak.getText();
                    }
                    break;
                    
                case 1       :
                    JumlahPembayaran = Float.parseFloat(txtJumlah.getText());
                    Jumlah = (int) Float.parseFloat(txtJumlah.getText());
                    JumlahPembayaran = (float) (JumlahPembayaran*250000);
                    Jumlah = (int) (Jumlah);
                    Harga = " Harga                           : Rp 250.000";
                    Merek = " Merek                           : NIKE";
                    Ucapan =" Ucapan Dari Kami    : Terima Kasih, Puas atau Tidak kami akan selalu memperbaiki pelayanan Kami !";
                    
                    if (ckHitam.isSelected()) {
                        Warna += ckHitam.getText() + ", ";
                    }
                    if (ckHijau.isSelected()) {
                        Warna += ckHijau.getText() + ", ";
                    }
                    if (ckBiru.isSelected()) {
                        Warna += ckBiru.getText() + ", ";
                    }
                    if (ckCampuran.isSelected()) {
                        Warna += ckCampuran.getText() + ", ";
                    }
                    if (ckTidak.isSelected()) {
                        Warna += ckTidak.getText() + ", ";
                    }else {
                        Warna = Warna.substring(0, Warna.length()-2) + ", ";
                    }
                    //
                    if (rdpuas.isSelected()){
                        Kepuasan = rdpuas.getText();
                    }else{
                        Kepuasan = rdtidak.getText();
                    }
                    break;
                    
                case 2       :
                    JumlahPembayaran = Float.parseFloat(txtJumlah.getText());
                    Jumlah = (int) Float.parseFloat(txtJumlah.getText());
                    JumlahPembayaran = (float) (JumlahPembayaran*150000);
                    Jumlah = (int) (Jumlah);
                    Harga = " Harga                           : Rp 150.000";
                    Merek = " Merek                           : VANS";
                    Ucapan =" Ucapan Dari Kami    : Terima Kasih, Puas atau Tidak kami akan selalu memperbaiki pelayanan Kami !";
                    
                    if (ckHitam.isSelected()) {
                        Warna += ckHitam.getText() + ", ";
                    }
                    if (ckHijau.isSelected()) {
                        Warna += ckHijau.getText() + ", ";
                    }
                    if (ckBiru.isSelected()) {
                        Warna += ckBiru.getText() + ", ";
                    }
                    if (ckCampuran.isSelected()) {
                        Warna += ckCampuran.getText() + ", ";
                    }
                    if (ckTidak.isSelected()) {
                        Warna += ckTidak.getText() + ", ";
                    }else {
                        Warna = Warna.substring(0, Warna.length()-2) + ", ";
                    }
                    
                    if (rdpuas.isSelected()){
                        Kepuasan = rdpuas.getText();
                    }else{
                        Kepuasan = rdtidak.getText();
                    }
                    break;
                    
                case 3       :
                    JumlahPembayaran = Float.parseFloat(txtJumlah.getText());
                    Jumlah = (int) Float.parseFloat(txtJumlah.getText());
                    JumlahPembayaran = (float) (JumlahPembayaran*175000);
                    Jumlah = (int) (Jumlah);
                    Harga = " Harga                           : Rp 175.000";
                    Merek = " Merek                           : EIGER";
                    Ucapan =" Ucapan Dari Kami    : Terima Kasih, Puas atau Tidak kami akan selalu memperbaiki pelayanan Kami !";
                   
                    if (ckHitam.isSelected()) {
                        Warna += ckHitam.getText() + ", ";
                    }
                    if (ckHijau.isSelected()) {
                        Warna += ckHijau.getText() + ", ";
                    }
                    if (ckBiru.isSelected()) {
                        Warna += ckBiru.getText() + ", ";
                    }
                    if (ckCampuran.isSelected()) {
                        Warna += ckCampuran.getText() + ", ";
                    }
                    if (ckTidak.isSelected()) {
                        Warna += ckTidak.getText() + ", ";
                    }else {
                        Warna = Warna.substring(0, Warna.length()-2) + ", ";
                    }
                    
                    if (rdpuas.isSelected()){
                        Kepuasan = rdpuas.getText();
                    }else{
                        Kepuasan = rdtidak.getText();
                    }
                    break;
                    
                case 4       :
                    JumlahPembayaran = Float.parseFloat(txtJumlah.getText());
                    Jumlah = (int) Float.parseFloat(txtJumlah.getText());
                    JumlahPembayaran = (float) (JumlahPembayaran*300000);
                    Jumlah = (int) (Jumlah);
                    Harga = " Harga                           : Rp 300.000";
                    Merek = " Merek                           : REY";
                    Ucapan =" Ucapan Dari Kami    : Terima Kasih, Puas atau Tidak kami akan selalu memperbaiki pelayanan Kami !";
                   
                    if (ckHitam.isSelected()) {
                        Warna += ckHitam.getText() + ", ";
                    }
                    if (ckHijau.isSelected()) {
                        Warna += ckHijau.getText() + ", ";
                    }
                    if (ckBiru.isSelected()) {
                        Warna += ckBiru.getText() + ", ";
                    }
                    if (ckCampuran.isSelected()) {
                        Warna += ckCampuran.getText() + ", ";
                    }
                    if (ckTidak.isSelected()) {
                        Warna += ckTidak.getText() + ", ";
                    }else {
                        Warna = Warna.substring(0, Warna.length()-2) + ", ";
                    }
                    
                    if (rdpuas.isSelected()){
                        Kepuasan = rdpuas.getText();
                    }else{
                        Kepuasan = rdtidak.getText();
                    }
                    break;
                   
                case 5       :
                    JumlahPembayaran = Float.parseFloat(txtJumlah.getText());
                    Jumlah = (int) Float.parseFloat(txtJumlah.getText());
                    JumlahPembayaran = (float) (JumlahPembayaran*275000);
                    Jumlah = (int) (Jumlah);
                    Harga = " Harga                           : Rp 275.000";
                    Merek = " Merek                           : BILABONG";
                    Ucapan =" Ucapan Dari Kami    : Terima Kasih, Puas atau Tidak kami akan selalu memperbaiki pelayanan Kami !";
                    
                    if (ckHitam.isSelected()) {
                        Warna += ckHitam.getText() + ", ";
                    }
                    if (ckHijau.isSelected()) {
                        Warna += ckHijau.getText() + ", ";
                    }
                    if (ckBiru.isSelected()) {
                        Warna += ckBiru.getText() + ", ";
                    }
                    if (ckCampuran.isSelected()) {
                        Warna += ckCampuran.getText() + ", ";
                    }
                    if (ckTidak.isSelected()) {
                        Warna += ckTidak.getText() + ", ";
                    }else {
                        Warna = Warna.substring(0, Warna.length()-2) + ", ";
                    }
                    
                    if (rdpuas.isSelected()){
                        Kepuasan = rdpuas.getText();
                    }else{
                        Kepuasan = rdtidak.getText();
                    }
                    break;
                //end dari data ComboBox Merek
            }
            // data untuk hasilnya
            hasil += Harga +"\n"+ Merek +"\n"+"Jumlah Pembayaran : "
                  + JumlahPembayaran + "\n"+ "Jumlah                         : " 
                  + Jumlah + "\n" 
                  +"Warna                           : "+Warna + "\n" 
                  +"Kepuasan Anda          : "+Kepuasan + "\n"
                  +"======="+Ucapan+ "\n" ;
            txthasil.setText(hasil);
            
            
    
            
    
           
            
            
               
            
        
            
           
        
        
    }//GEN-LAST:event_btnBayarkanActionPerformed

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaiActionPerformed
        // Perintah untuk Keluar dari Apliaksi Tersebut :
        System.exit(0);
    }//GEN-LAST:event_btnSelesaiActionPerformed

    private void btnBersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBersihkanActionPerformed
        // Untuk Membersihkan Data yang dihasilkan:
        txtJumlah.setText("");
        cmbMerek.setSelectedIndex(0);
        txthasil.setText("");
    }//GEN-LAST:event_btnBersihkanActionPerformed

    private void ckHitamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckHitamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckHitamActionPerformed

    private void rdpuasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdpuasActionPerformed
        // TODO add your handling code here:
       

    }//GEN-LAST:event_rdpuasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jframe_Tas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jframe_Tas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jframe_Tas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jframe_Tas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jframe_Tas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBayarkan;
    private javax.swing.JButton btnBersihkan;
    private javax.swing.JButton btnSelesai;
    private javax.swing.ButtonGroup btngnilai;
    private javax.swing.JCheckBox ckBiru;
    private javax.swing.JCheckBox ckCampuran;
    private javax.swing.JCheckBox ckHijau;
    private javax.swing.JCheckBox ckHitam;
    private javax.swing.JCheckBox ckTidak;
    private javax.swing.JComboBox<String> cmbMerek;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdpuas;
    private javax.swing.JRadioButton rdtidak;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextArea txthasil;
    // End of variables declaration//GEN-END:variables
}
